### Libraries

In [1]:
import numpy as np

#### Preliminary Definitions

In [2]:
A = np.array([[2.,-1.,0.,0.,0.],[-1.,2.,-1.,0.,0.],[0.,-1.,2.,-1.,0.]
              ,[0.,0.,-1.,2.,-1.],[0.,0.,0.,-1.,2.]])
b = np.array([1., 2., 3., 4., 5.])
N = A.shape[0]
x = np.zeros(N)

In [3]:
A

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [4]:
a = np.concatenate((np.array([0.]),np.array([A[i+1,i] for i in range(N-1)])))
d = np.array([A[i,i] for i in range(N)])
c = np.concatenate((np.array([A[i,i+1] for i in range(N-1)]),np.array([0.])))

In [5]:
a

array([ 0., -1., -1., -1., -1.])

In [6]:
d

array([ 2.,  2.,  2.,  2.,  2.])

In [7]:
c

array([-1., -1., -1., -1.,  0.])

#### Gaussian Elimination

In [8]:
for i in range(1,N):
    m = a[i]/d[i-1]
    d[i] = d[i] - m*c[i-1]
    b[i] = b[i] - m*b[i-1]

In [9]:
x[N-1] = b[N-1]/d[N-1]
for i in range(N-1)[::-1]:
    x[i] = (b[i] - c[i]*x[i+1])/d[i]
x

array([  5.83333333,  10.66666667,  13.5       ,  13.33333333,   9.16666667])

In [10]:
np.dot(A,x)

array([ 1.,  2.,  3.,  4.,  5.])